INSERT INTO GRADE_REPORT VALUES(17,112,'B');

INSERT INTO GRADE_REPORT VALUES(17,119,'C');

INSERT INTO GRADE_REPORT VALUES(8,85,'A');

INSERT INTO GRADE_REPORT VALUES(8,92,'A');

INSERT INTO GRADE_REPORT VALUES(8,102,'B');

INSERT INTO GRADE_REPORT VALUES(8,135,'A');